### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by mageuser** [kiwicommerce/magento2-login-as-customer#1]
Hello, I want know if this module is safe to use on a live prouction site?

Thanks.

**Comment by dankhrapiyush** [comment]
Hello @kauansoft,

Yes, you can use on a live prouction site but I recommend to first check on your development site before installing on the live.

Please check demo on [Magento 2 – Login As Customer](https://kiwicommerce.co.uk/extensions/magento2-login-as-customer/) page to make sure how it's working.

If need any additional support then feel free to [contact us](https://kiwicommerce.co.uk/get-in-touch/).

Thank you.
